server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.92.133:3306/db_authority_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jackson:
    #JSON\u65E5\u671F\u683C\u5F0F\u5316
    date-format: yyyy-MM-dd
    #JSON\u65E5\u671F\u683C\u5F0F\u5316\u8BBE\u7F6E\u65F6\u533A\u4E3A\u4E0A\u6D77
    time-zone: Asia/Shanghai
  mvc:
    format:
      #\u65E5\u671F\u683C\u5F0F\u5316
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #\u8BBE\u7F6E\u522B\u540D
  type-aliases-package: com.wyl.entity
    #\u5173\u95ED\u9A7C\u5CF0\u547D\u540D\u6620\u5C04
  #configuration:
  #map-underscore-to-camel-case: false
#\u663E\u793A\u65E5\u5FD7
logging:
  level:
    com.wyl.dao: debug
#jwt设置
jwt:
  secret: com.wyl
  expiration: 1800000

