server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.92.133:3306/db_authority_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jackson:
    #JSON日期格式化
    date-format: yyyy-MM-dd
    #JSON日期格式化设置时区为上海
    time-zone: Asia/Shanghai
  mvc:
    format:
      #日期格式化
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
  #redis配置
  redis:
    host: 192.168.92.133
    port: 6379
    database: 0
    timeout: 10000
    #自定义属性 redis过期时间
    expire: 60000
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #设置别名
  type-aliases-package: com.wyl.entity
  #关闭驼峰命名映射
  #configuration:
  #map-underscore-to-camel-case: false
#显示日志
logging:
  level:
    com.wyl.dao: debug
#jwt设置
jwt:
  secret: com.wyl
  expiration: 1800000
#登录请求地址(自定义)
request:
  login:
    url: /api/user/login

